services:
  - type: web
    name: vaultless-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key
      - key: MAIL_USERNAME
        value: your-email@gmail.com
      - key: MAIL_PASSWORD
        value: your-app-password
      - key: DATABASE_URL
        fromDatabase:
          name: vaultless-db
          property: connectionString

databases:
  - name: vaultless-db
    plan: free
